-   repo: https://github.com/pre-commit/pre-commit-hooks
    sha: v0.9.1
    hooks:
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: check-yaml
-   repo: https://git.shore.co.il/nimrod/shell-pre-commit.git
    sha: v0.5.4
    hooks:
    -   id: shell-lint
        files: &shellscripts '^merge-conflict$'
    -   id: shellcheck
        files: *shellscripts
-   repo: https://git.shore.co.il/nimrod/git-pre-commit.git
    sha: v0.1.1
    hooks:
    -   id: merge-conflict
