---
language: python
python: "3.6"
dist: trusty
sudo: false
group: beta
cache:
  - pip
  - directories:
      - $HOME/.pre-commit
      - $HOME/.cabal
      - $HOME/.ghc

addons:
  apt:
    packages:
      - cabal-install
      - ghc

env:
    PATH: "$HOME/bats/bin:$HOME/.cabal/bin:$PATH"

install:
  - cabal update && cabal install shellcheck
  - pip install pre_commit | cat
  - git clone --depth 1 https://github.com/sstephenson/bats.git "$HOME/bats"

script:
  - pre-commit run --all-files

notifications:
  on_failure: never
  email: false
