#!/bin/sh
set -eu

dest="${1:-master}"
current="$(git symbolic-ref --short HEAD)" || exit 0  # Detached head.

[ "$current" != "$dest" ] || exit 0

patch="$(git format-patch "$(git merge-base HEAD "$dest")..$dest" --stdout)"

[ "$patch" != "" ] || exit 0

echo "$patch" | git apply --check -
